# Generated by Django 4.0.5 on 2022-07-06 21:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('height', models.IntegerField()),
                ('years_old', models.IntegerField()),
                ('favorite_toy', models.CharField(max_length=20)),
                ('friendly', models.BooleanField()),
            ],
        ),
    ]
