# Generated by Django 4.0.5 on 2022-07-04 01:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('breeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('weight', models.FloatField()),
                ('height', models.IntegerField()),
                ('years_old', models.IntegerField()),
                ('favorite_toy', models.CharField(max_length=20)),
                ('friendly', models.BooleanField()),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='breeds.breeds')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='users.users')),
            ],
        ),
    ]
