# Generated by Django 4.0.5 on 2022-07-06 21:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('characteristic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal', to='groups.groups')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal', to='characteristic.characteristic')),
            ],
        ),
    ]
