# Generated by Django 4.0.5 on 2022-07-07 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristic', '0001_initial'),
        ('groups', '0001_initial'),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='characteristic',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristic.characteristic'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groups'),
        ),
    ]
