# Generated by Django 4.0.5 on 2022-07-07 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('animals', '0002_alter_animals_characteristic_alter_animals_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animals',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='groups.groups'),
        ),
    ]
